import TelegramBot from 'node-telegram-bot-api';
import { config } from '../config';
import { ProjectIdea, DailyReport, BuildSpecification } from '../types';
import { MemeTrend } from '../services/memeTrends';
import { AIAgentIdea } from '../analysis/aiAgentGenerator';

let bot: TelegramBot | null = null;

/**
 * Initialize the Telegram bot
 */
export function initTelegramBot(): TelegramBot {
    if (!config.telegram.botToken) {
        throw new Error('TELEGRAM_BOT_TOKEN is not set');
    }

    bot = new TelegramBot(config.telegram.botToken, { polling: false });
    console.log('✅ Telegram bot initialized');
    return bot;
}

/**
 * Send the daily report to Telegram
 */
export async function sendDailyReport(report: DailyReport): Promise<void> {
    if (!bot) {
        bot = initTelegramBot();
    }

    const chatId = config.telegram.chatId;
    if (!chatId) {
        throw new Error('TELEGRAM_CHAT_ID is not set');
    }

    // Send header message
    const headerMessage = formatHeader(report);
    await bot.sendMessage(chatId, headerMessage, { parse_mode: 'Markdown' });

    // Send each idea as a separate message for better readability
    for (const idea of report.ideas) {
        const ideaMessage = formatIdea(idea);
        await bot.sendMessage(chatId, ideaMessage, { parse_mode: 'Markdown' });
        // Small delay to avoid rate limiting
        await sleep(500);
    }

    // Send footer with market summary
    const footerMessage = formatFooter(report);
    await bot.sendMessage(chatId, footerMessage, { parse_mode: 'Markdown' });

    console.log(`✅ Sent ${report.ideas.length} ideas to Telegram`);
}

/**
 * Format the header message
 */
function formatHeader(report: DailyReport): string {
    return `
🚀 *CRYPTO AI DAILY REPORT*
📅 ${report.date}

━━━━━━━━━━━━━━━━━━━
📊 *Today's Top ${report.ideas.length} Ideas*
━━━━━━━━━━━━━━━━━━━
`;
}

/**
 * Format a single project idea
 */
function formatIdea(idea: ProjectIdea): string {
    const scoreEmoji = getScoreEmoji(idea.score);
    const simplicityEmoji = idea.launchSimplicity === 'Easy' ? '🟢' : idea.launchSimplicity === 'Medium' ? '🟡' : '🔴';

    return `
🔹 *IDEA #${idea.id}: ${idea.name}*
💎 Ticker: \`$${idea.ticker}\`
${scoreEmoji} Score: ${idea.score}/10

📝 *Narrative:*
${idea.narrative}

💡 *Concept:*
${idea.concept}

⏰ *Why Now:*
${idea.whyNow}

🎯 *Token Utility:*
${idea.tokenUtility}

${simplicityEmoji} *Launch Simplicity:* ${idea.launchSimplicity}

🐦 *Twitter Hook:*
_${idea.twitterHook}_

📌 Sources: ${idea.sources.join(', ')}

━━━━━━━━━━━━━━━━━━━
`;
}

/**
 * Format the footer message
 */
function formatFooter(report: DailyReport): string {
    const topTokens = report.marketSnapshot.trendingTokens
        .slice(0, 5)
        .map((t) => `• ${t.symbol}: ${t.priceChange24h > 0 ? '+' : ''}${t.priceChange24h.toFixed(1)}%`)
        .join('\n');

    const hotTopics = report.marketSnapshot.hotTopics
        .slice(0, 5)
        .map((t) => `• ${t.keyword} (${t.sentiment})`)
        .join('\n');

    return `
📈 *MARKET SNAPSHOT*

*Trending Tokens:*
${topTokens || '• No data available'}

*Hot Topics on X:*
${hotTopics || '• No data available'}

*AI Agent Trends:*
${report.marketSnapshot.aiAgentTrends.slice(0, 3).map((t) => `• ${t}`).join('\n') || '• No data available'}

━━━━━━━━━━━━━━━━━━━
🤖 Generated by Crypto AI Automation
⏰ ${report.generatedAt.toISOString()}
`;
}

/**
 * Get emoji based on score
 */
function getScoreEmoji(score: number): string {
    if (score >= 8) return '🔥';
    if (score >= 6) return '⭐';
    if (score >= 4) return '💫';
    return '💭';
}

/**
 * Send a simple text message
 */
export async function sendMessage(text: string): Promise<void> {
    if (!bot) {
        bot = initTelegramBot();
    }

    const chatId = config.telegram.chatId;
    if (!chatId) {
        throw new Error('TELEGRAM_CHAT_ID is not set');
    }

    await bot.sendMessage(chatId, text, { parse_mode: 'Markdown' });
}

/**
 * Send an error notification
 */
export async function sendError(error: string): Promise<void> {
    try {
        await sendMessage(`⚠️ *Error in Crypto AI Automation*\n\n${error}`);
    } catch (e) {
        console.error('Failed to send error notification:', e);
    }
}

// Helper
function sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Send meme trends to Telegram
 */
export async function sendMemeTrends(trends: MemeTrend[]): Promise<void> {
    if (!bot) {
        bot = initTelegramBot();
    }

    const chatId = config.telegram.chatId;
    if (!chatId) {
        throw new Error('TELEGRAM_CHAT_ID is not set');
    }

    const header = `
🎭 *VIRAL MEME TRENDS*
📅 ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}

━━━━━━━━━━━━━━━━━━━
🔥 *Hot Trends for Meme-Making*
━━━━━━━━━━━━━━━━━━━
`;

    await bot.sendMessage(chatId, header, { parse_mode: 'Markdown' });
    await sleep(300);

    for (const trend of trends) {
        const viralEmoji = trend.virality === 'Exploding' ? '💥' : trend.virality === 'Hot' ? '🔥' : '📈';
        const platformEmoji = trend.platform === 'X' ? '🐦' : trend.platform === 'TikTok' ? '📱' : '🌐';

        const trendMessage = `
${viralEmoji} *${trend.name}*
${platformEmoji} Platform: ${trend.platform}

📝 *What it is:*
${trend.description}

💡 *Meme Idea:*
_${trend.memeIdea}_

━━━━━━━━━━━━━━━━━━━
`;
        await bot.sendMessage(chatId, trendMessage, { parse_mode: 'Markdown' });
        await sleep(300);
    }

    const footer = `
🎨 *CRYPTO MEME IDEAS*

• 🐕 *$CHILL* - Chill Guy unbothered by red candles
• 🦐 *$PRAWN* - High cortisol degen trader vibes  
• 🦍 *$GORILLA* - 100 Rugs vs 1 Diamond Hand
• 😮‍💨 *$BURNOUT* - End of year exhaustion token
• 🎄 *$XMAS* - Holiday chaos memecoin

━━━━━━━━━━━━━━━━━━━
🤖 Pick one and make it viral!
`;

    await bot.sendMessage(chatId, footer, { parse_mode: 'Markdown' });
    console.log(`✅ Sent ${trends.length} meme trends to Telegram`);
}

/**
 * Send AI Agent ideas with build prompts to Telegram
 */
export async function sendAIAgentIdeas(ideas: AIAgentIdea[]): Promise<void> {
    if (!bot) {
        bot = initTelegramBot();
    }

    const chatId = config.telegram.chatId;
    if (!chatId) {
        throw new Error('TELEGRAM_CHAT_ID is not set');
    }

    // Send header
    const header = `
🤖 *AI AGENT IDEAS FOR TRADERS*
📅 ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}

━━━━━━━━━━━━━━━━━━━
💡 *${ideas.length} AI Agent Solutions*
━━━━━━━━━━━━━━━━━━━
`;

    await bot.sendMessage(chatId, header, { parse_mode: 'Markdown' });
    await sleep(300);

    // Send each idea
    for (const idea of ideas) {
        const scoreEmoji = idea.score >= 8 ? '🔥' : idea.score >= 7 ? '⭐' : '💫';

        // Send idea summary with type indicator
        const getTypeEmoji = (type: string) => {
            switch (type) {
                case 'AI Agent': return '🤖';
                case 'Real Project': return '💡';
                case 'Gaming': return '🎮';
                case 'DeFi': return '💰';
                case 'Privacy': return '🔒';
                default: return '✨';
            }
        };
        const typeEmoji = getTypeEmoji(idea.ideaType);
        const ideaMessage = `
${typeEmoji} *${idea.ideaType?.toUpperCase() || 'IDEA'} #${idea.id}: ${idea.name}*
📂 Category: ${idea.category}
🔧 Type: ${idea.projectType || 'Project'}
📊 Score: ${idea.score}/10
${idea.problemSource ? `🔍 ${idea.problemSource}` : ''}
${idea.trendingContext ? `📈 ${idea.trendingContext}` : ''}

❌ *Real Problem:*
"${idea.problem}"

✅ *Solution:*
${idea.solution}

👤 *Target User:*
${idea.targetUser}

⚙️ *Key Features:*
${idea.features.map(f => `• ${f}`).join('\n')}

🛠 *Tech Stack:*
${idea.techStack.join(' | ')}

━━━━━━━━━━━━━━━━━━━
`;
        await bot.sendMessage(chatId, ideaMessage, { parse_mode: 'Markdown' });
        await sleep(300);

        // Send build prompt as separate message (plain text to avoid markdown issues)
        const promptMessage = `📋 BUILD PROMPT FOR: ${idea.name}

${idea.buildPrompt}`;

        // Split long prompts if needed
        if (promptMessage.length > 4000) {
            const parts = splitMessage(promptMessage, 4000);
            for (const part of parts) {
                await bot.sendMessage(chatId, part);
                await sleep(200);
            }
        } else {
            await bot.sendMessage(chatId, promptMessage);
        }

        await sleep(500);
    }

    // Send footer
    const footer = `
━━━━━━━━━━━━━━━━━━━
✅ *${ideas.length} AI Agent Ideas Delivered*

💻 Copy any BUILD PROMPT above and paste it into your AI coding assistant to start building!

🤖 Generated by Crypto AI Automation
`;

    await bot.sendMessage(chatId, footer, { parse_mode: 'Markdown' });
    console.log(`✅ Sent ${ideas.length} AI agent ideas with build prompts to Telegram`);
}

/**
 * Split long messages into parts
 */
function splitMessage(text: string, maxLength: number): string[] {
    const parts: string[] = [];
    let remaining = text;

    while (remaining.length > 0) {
        if (remaining.length <= maxLength) {
            parts.push(remaining);
            break;
        }

        // Find a good break point
        let breakPoint = remaining.lastIndexOf('\n', maxLength);
        if (breakPoint === -1 || breakPoint < maxLength / 2) {
            breakPoint = maxLength;
        }

        parts.push(remaining.substring(0, breakPoint));
        remaining = remaining.substring(breakPoint);
    }

    return parts;
}

/**
 * Send Build Specifications to Telegram (new enhanced format)
 */
export async function sendBuildSpecifications(specs: BuildSpecification[]): Promise<void> {
    if (!bot) {
        bot = initTelegramBot();
    }

    const chatId = config.telegram.chatId;
    if (!chatId) {
        throw new Error('TELEGRAM_CHAT_ID is not set');
    }

    // Send header
    const header = `
🚀 *BUILD SPECIFICATIONS*
📅 ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}

━━━━━━━━━━━━━━━━━━━
🔧 *${specs.length} Project Specs Generated*
━━━━━━━━━━━━━━━━━━━
`;

    await bot.sendMessage(chatId, header, { parse_mode: 'Markdown' });
    await sleep(300);

    // Send each Build Spec
    for (let i = 0; i < specs.length; i++) {
        const spec = specs[i];
        const scoreEmoji = spec.score >= 80 ? '🔥' : spec.score >= 60 ? '⭐' : '💫';

        // Main spec message
        const specMessage = `
${scoreEmoji} *#${i + 1}: ${spec.projectName}*
💎 Ticker: \`${spec.ticker}\`
📊 Score: ${spec.score}/100

💡 *Concept:*
${spec.concept}

⏰ *Why Now (Alpha):*
${spec.whyNow}

${spec.marketingHook ? `🎯 *Marketing Hook:*\n_"${spec.marketingHook}"_\n` : ''}
━━━━━━━━━━━━━━━━━━━
`;
        await bot.sendMessage(chatId, specMessage, { parse_mode: 'Markdown' });
        await sleep(200);

        // Tech Stack message
        const techMessage = `
🛠 *TECH STACK for ${spec.ticker}*

• *Frontend:* ${spec.techStack.frontend}
• *Blockchain:* ${spec.techStack.blockchain}
• *Backend:* ${spec.techStack.backend}
• *Database:* ${spec.techStack.database}
• *Wallet:* ${spec.techStack.wallet}
${spec.techStack.dataFetching ? `• *Data Fetching:* ${spec.techStack.dataFetching}` : ''}
${spec.techStack.realtime ? `• *Realtime:* ${spec.techStack.realtime}` : ''}

⚙️ *Core Features:*
${spec.coreFeatures.map(f => `• ${f}`).join('\n')}
`;
        await bot.sendMessage(chatId, techMessage, { parse_mode: 'Markdown' });
        await sleep(200);

        // Database Schema
        if (Object.keys(spec.databaseSchema).length > 0) {
            let schemaText = `📋 *DATABASE SCHEMA for ${spec.ticker}*\n\n`;
            for (const [table, fields] of Object.entries(spec.databaseSchema)) {
                schemaText += `*${table}:*\n\`${fields}\`\n\n`;
            }
            await bot.sendMessage(chatId, schemaText, { parse_mode: 'Markdown' });
            await sleep(200);
        }

        // Smart Contract Requirements
        if (spec.smartContractRequirements.length > 0) {
            const contractText = `
📜 *SMART CONTRACT REQUIREMENTS*
${spec.smartContractRequirements.map(r => `• ${r}`).join('\n')}
`;
            await bot.sendMessage(chatId, contractText, { parse_mode: 'Markdown' });
            await sleep(200);
        }

        // Analysis Logic (if available)
        if (spec.analysisLogic) {
            const analysisText = `
🎯 *SMART MONEY ANALYSIS LOGIC*
${spec.analysisLogic.smartMoneyFilters?.map(f => `• ${f}`).join('\n') || ''}
${spec.analysisLogic.signalGeneration ? `\n📡 *Signal:* ${spec.analysisLogic.signalGeneration}` : ''}
`;
            await bot.sendMessage(chatId, analysisText, { parse_mode: 'Markdown' });
            await sleep(200);
        }

        // Performance Specs (if available)
        if (spec.performanceSpecs) {
            const perfText = `
⚡ *PERFORMANCE SPECS*
${spec.performanceSpecs.caching ? `• *Caching:* ${spec.performanceSpecs.caching}` : ''}
${spec.performanceSpecs.realtime ? `• *Realtime:* ${spec.performanceSpecs.realtime}` : ''}
${spec.performanceSpecs.rateLimit ? `• *Rate Limit:* ${spec.performanceSpecs.rateLimit}` : ''}
`;
            await bot.sendMessage(chatId, perfText, { parse_mode: 'Markdown' });
            await sleep(200);
        }

        // Roadmap (plain text to avoid markdown issues)
        const roadmapText = `📍 ROADMAP for ${spec.ticker}

${spec.roadmap.map((step, idx) => `${idx + 1}. ${step.replace('Step ' + (idx + 1) + ': ', '')}`).join('\n')}

━━━━━━━━━━━━━━━━━━━`;

        // Split if too long
        if (roadmapText.length > 4000) {
            const parts = splitMessage(roadmapText, 4000);
            for (const part of parts) {
                await bot.sendMessage(chatId, part);
                await sleep(200);
            }
        } else {
            await bot.sendMessage(chatId, roadmapText);
        }

        await sleep(500);
    }

    // Footer
    const footer = `
✅ *${specs.length} Build Specifications Delivered!*

💻 Copy and paste these specs to your AI coding assistant to start building!

🤖 Generated by Crypto AI Automation
⏰ ${new Date().toISOString()}
`;

    await bot.sendMessage(chatId, footer, { parse_mode: 'Markdown' });
    console.log(`✅ Sent ${specs.length} Build Specifications to Telegram`);
}

